#tocmat设置
server:
  port: 9002
  context-path: /
  tomcat:
    uri-encoding: UTF-8
  #    允许的http请求
  port-header: HEAD,PUT,DELETE,OPTIONS,TRACE,COPY,SEARCH,PROPFIND
  #  是否启用响应压缩
  compression:
    enabled: true
spring:
  devtools:
    restart:
      #      热部署生效
      enabled: true
  #限制上传文件大小，springboot默认限制为2M
  servlet:
    multipart:
      enabled: true
      #      单个文件大小
      max-file-size: 10MB
      #      单次请求文件大小，为了应对多个文件同时上传的情况
      max-request-size: 50MB
  # class文件编码
  mandatory-file-encoding: UTF-8
  #    datasource
  ## 数据库配置
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    #    driverClassName: com.mysql.cj.jdbc.Driver
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://${backup.databaseHost}:3306/${backup.databaseName}?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8&allowMultiQueries=true
    username: ${backup.username}
    password: ${backup.password}
    ##  Hikari 连接池配置 ------ 详细配置请访问：https://github.com/brettwooldridge/HikariCP
    ## 最小空闲连接数量
    hikari:
      minimum-idle: 5
      ## 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      ## 连接池最大连接数，默认是10
      maximum-pool-size: 10
      ## 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      ## 连接池母子
      pool-name: MyHikariCP
      ## 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      ## 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  #     控制台彩色输出
  output:
    ansi:
      enabled: ALWAYS
  #      应对OPTIONS请求，权限判断会出现此请求
  mvc:
    dispatch-options-request: true
    #    默认静态路径
    static-path-pattern: /**
  resources:
    static-locations: classpath:/static/,classpath:/error/,file:${file.up-path}

  #    是否启用aop
  aop:
    auto: true
  #  配置email
  mail:
    host: smtp.qq.com
    username: xuesemofa@vip.qq.com
    password: dowahhazzapqbcja
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
#banner 启动动画文件
# 启动动画文件编码
banner:
  charset: UTF-8

#配置日志
logging:
  #  默认日志格式 10M自动分割 最多存在7个文件
  file: ytsoaBackstage.log
  level:
    com.yts.ytsoa: debug
    #默认分页条数
page:
  page-size: 15
#    文件上传下载路径设定
file:
  #  模板地址
  file-model: D://
  #文件下载暂存路径
  dow-path: D://
  #  文件上传路径
  up-path: D://
  #  允许的上传类型,多个类型用‘,’隔开
  up-prefix: jpg,png,doc,docx,xls,xlsx,zip,7z,rar
  #  备份地址
  back-path: D://
#  数据库连接设置
backup:
  mysqldump: C:\Program Files\MySQL\MySQL Server 5.7\bin
  databaseName: ytsoa
  databaseHost: 192.168.1.222
  username: root
  password: root